name: My workflow
on: [push, pull_request]
jobs:
  test:
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    runs-on: ubuntu-latest
    steps:
    - uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
        channel: '#na'
        message: ${{ steps.ruby_script.outputs.available }}
        if: steps.ruby_script.outputs.available == 'false'
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: gem install open-uri
    - run: gem install net-http
    - run: gem install nokogiri
    - id: ruby_script
      run: echo "available=$((ruby main.rb))"
