name: My workflow
on:
  schedule:
  - cron: "0/15 * * * *"
jobs:
  run_script:
    runs-on: ubuntu-latest
    outputs:
      available: ${{ steps.ruby_script.outputs.available }}
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: gem install open-uri
    - run: gem install net-http
    - run: gem install nokogiri
    - id: ruby_script
      run: echo "available=$(ruby main.rb)" >> $GITHUB_OUTPUT
  send_slack:
    needs: run_script
    if: needs.run_script.outputs.available == 'true'
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: act10ns/slack@v1
        with:
            status: ${{ job.status }}
            channel: '#na'
            message:  https://www.goest.us/kuroneko-sama-mr-black-cat-candle/ is available!!!
